import 'dart:ui';

import 'package:flutter/material.dart';

TextStyle fromTextStyle(
  TextStyle given, {
  bool? inherit,
  Color? color,
  Color? backgroundColor,
  double? fontSize,
  FontWeight? fontWeight,
  FontStyle? fontStyle,
  double? letterSpacing,
  double? wordSpacing,
  TextBaseline? textBaseline,
  double? height,
  TextLeadingDistribution? leadingDistribution,
  Locale? locale,
  Paint? foreground,
  Paint? background,
  List<Shadow>? shadows,
  List<FontFeature>? fontFeatures,
  TextDecoration? decoration,
  Color? decorationColor,
  TextDecorationStyle? decorationStyle,
  double? decorationThickness,
  String? debugLabel,
  String? fontFamily,
  List<String>? fontFamilyFallback,
  String? package,
  TextOverflow? overflow,
}) =>
    TextStyle(
      inherit: inherit ?? given.inherit,
      color: color ?? given.color,
      backgroundColor: backgroundColor ?? given.backgroundColor,
      fontSize: fontSize ?? given.fontSize,
      fontWeight: fontWeight ?? given.fontWeight,
      fontStyle: fontStyle ?? given.fontStyle,
      letterSpacing: letterSpacing ?? given.letterSpacing,
      wordSpacing: wordSpacing ?? given.wordSpacing,
      textBaseline: textBaseline ?? given.textBaseline,
      height: height ?? given.height,
      leadingDistribution: leadingDistribution ?? given.leadingDistribution,
      locale: locale ?? given.locale,
      foreground: foreground ?? given.foreground,
      background: background ?? given.background,
      shadows: shadows ?? given.shadows,
      fontFeatures: fontFeatures ?? given.fontFeatures,
      decoration: decoration ?? given.decoration,
      decorationColor: decorationColor ?? given.decorationColor,
      decorationStyle: decorationStyle ?? given.decorationStyle,
      decorationThickness: decorationThickness ?? given.decorationThickness,
      debugLabel: debugLabel ?? given.debugLabel,
      fontFamily: fontFamily ?? given.fontFamily,
      fontFamilyFallback: fontFamilyFallback ?? given.fontFamilyFallback,
      overflow: overflow ?? given.overflow,
      package: package,
    );

extension CloneTextStyleExtension on TextStyle {
  TextStyle fromTextStyle(
    TextStyle given, {
    bool? inherit,
    Color? color,
    Color? backgroundColor,
    double? fontSize,
    FontWeight? fontWeight,
    FontStyle? fontStyle,
    double? letterSpacing,
    double? wordSpacing,
    TextBaseline? textBaseline,
    double? height,
    TextLeadingDistribution? leadingDistribution,
    Locale? locale,
    Paint? foreground,
    Paint? background,
    List<Shadow>? shadows,
    List<FontFeature>? fontFeatures,
    TextDecoration? decoration,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
    double? decorationThickness,
    String? debugLabel,
    String? fontFamily,
    List<String>? fontFamilyFallback,
    String? package,
    TextOverflow? overflow,
  }) =>
      TextStyle(
        inherit: inherit ?? given.inherit,
        color: color ?? given.color,
        backgroundColor: backgroundColor ?? given.backgroundColor,
        fontSize: fontSize ?? given.fontSize,
        fontWeight: fontWeight ?? given.fontWeight,
        fontStyle: fontStyle ?? given.fontStyle,
        letterSpacing: letterSpacing ?? given.letterSpacing,
        wordSpacing: wordSpacing ?? given.wordSpacing,
        textBaseline: textBaseline ?? given.textBaseline,
        height: height ?? given.height,
        leadingDistribution: leadingDistribution ?? given.leadingDistribution,
        locale: locale ?? given.locale,
        foreground: foreground ?? given.foreground,
        background: background ?? given.background,
        shadows: shadows ?? given.shadows,
        fontFeatures: fontFeatures ?? given.fontFeatures,
        decoration: decoration ?? given.decoration,
        decorationColor: decorationColor ?? given.decorationColor,
        decorationStyle: decorationStyle ?? given.decorationStyle,
        decorationThickness: decorationThickness ?? given.decorationThickness,
        debugLabel: debugLabel ?? given.debugLabel,
        fontFamily: fontFamily ?? given.fontFamily,
        fontFamilyFallback: fontFamilyFallback ?? given.fontFamilyFallback,
        overflow: overflow ?? given.overflow,
        package: package,
      );
}
