name: ravencoin_back
description: Ravencoin wallet backend library
version: 1.0.0

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  bs58check: ^1.0.2
  collection: ^1.16.0
  crypto: ^3.0.2
  encrypt: ^5.0.1
  equatable: ^2.0.5
  hive: ^2.2.3
  ordered_set: ^5.0.0
  pointycastle: ^3.6.2
  quiver: ^3.1.0
  ravencoin_wallet: ^3.0.0
  ravencoin_electrum: ^2.0.0
  proclaim: ^4.0.1
  rxdart: ^0.27.5
  sorted_list: ^1.0.0
  http: ^0.13.5
  ulid: ^2.0.0
  tuple: ^2.0.0
  intl: ^0.17.0
  serverpod_client: ^0.9.8

dev_dependencies:
  build_runner: ^2.0.0
  date_format: ^2.0.4
  dotenv: ^3.0.0
  hive_generator: ^1.1.0
  pedantic: ^1.10.0
  test: ^1.17.12

dependency_overrides:
  proclaim:
    path: ../../proclaim
  ravencoin_electrum:
    path: ../../ravencoin_electrum
  ravencoin_wallet:
    path: ../../ravencoin_wallet
