name: Bug
description: File a bug report
labels: ['Bug']
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: describe-the-bug
    attributes:
      label: Describe The Bug
      description: A clear and concise description of the bug.
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: to-reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: Tell us the steps you took!
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: Tell us what you expected!
    validations:
      required: true
  - type: textarea
    id: log-output
    attributes:
      label: Log Output
      description: If applicable, provide relevant log output. No need for backticks here.
      render: shell
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Add screenshots to help explain the problem.
      placeholder: Drag-and-drop screenshots or screen recordings here!
    validations:
      required: false
  - type: textarea
    id: tasks
    attributes:
      label: Tasks For This Bug
      description: Add any tasks that are required for this bug.
      placeholder: Create a list of tasks!
      value: ' - [ ] #'
    validations:
      required: false
