name: raven_back
description: Ravencoin wallet backend library
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  bs58check: ^1.0.2
  collection: ^1.15.0
  crypto: ^3.0.0
  encrypt: ^5.0.0
  equatable: ^2.0.3
  hive: ^2.0.4
  ordered_set: ^3.1.0
  pointycastle: ^3.3.4
  quiver: ^3.0.1
  ravencoin_wallet: ^3.0.0
  raven_electrum: ^2.0.0
  reservoir: ^4.0.1
  rxdart: ^0.27.3
  sorted_list: ^1.0.0
  http: ^0.13.3
  ulid: ^2.0.0
  tuple: ^2.0.0
  intl: ^0.17.0

dev_dependencies:
  build_runner: ^2.0.0
  date_format: ^2.0.4
  dotenv: ^3.0.0
  hive_generator: ^1.1.0
  pedantic: ^1.10.0
  test: ^1.17.12

dependency_overrides:
  reservoir:
    path: ../reservoir
  raven_electrum:
    path: ../raven_electrum
  ravencoin_wallet:
    path: ../ravencoin_wallet
