# Defines a default set of lint rules enforced for projects at Google. For
# details and rationale, see
# https://github.com/dart-lang/pedantic#enabled-lints.

#include: package:pedantic/analysis_options.yaml

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.

# Uncomment to specify additional rules.
# linter:
#   rules:
#     - camel_case_types
linter:
  rules:
    avoid_print: false
    prefer_relative_imports: false
    omit_local_variable_types: false   
    implementation_imports: false
    constant_identifier_names: false
    # add more here ...
    # Available lints see: [https://dart-lang.github.io/linter/lints/index.html][1]

# // ignore: sort_constructors_first

# analyzer:
#   exclude:
#     - path/to/excluded/files/**