/// here is the list, but will have to be updated when country_icons updates
const Map<String, String> countryIconsCodes = {
  'ad': 'Andorra',
  'ae': 'United Arab Emirates',
  'af': 'Afghanistan',
  'ag': 'Antigua and Barbuda',
  'ai': 'Anguilla',
  'al': 'Albania',
  'am': 'Armenia',
  'ao': 'Angola',
  'aq': 'Antarctica',
  'ar': 'Argentina',
  'as': 'American Samoa',
  'at': 'Austria',
  'au': 'Australia',
  'aw': 'Aruba',
  'ax': 'Åland Islands',
  'az': 'Azerbaijan',
  'ba': 'Bosnia and Herzegovina',
  'bb': 'Barbados',
  'bd': 'Bangladesh',
  'be': 'Belgium',
  'bf': 'Burkina Faso',
  'bg': 'Bulgaria',
  'bh': 'Bahrain',
  'bi': 'Burundi',
  'bj': 'Benin',
  'bl': 'Saint Barthélemy',
  'bm': 'Bermuda',
  'bn': 'Brunei',
  'bo': 'Bolivia',
  'bq': 'Caribbean Netherlands (Bonaire, Sint Eustatius, and Saba)',
  'br': 'Brazil',
  'bs': 'Bahamas',
  'bt': 'Bhutan',
  'bv': 'Bouvet Island',
  'bw': 'Botswana',
  'by': 'Belarus',
  'bz': 'Belize',
  'ca': 'Canada',
  'cc': 'Cocos (Keeling) Islands',
  'cd': 'Democratic Republic of the Congo (DR Congo)',
  'cf': 'Central African Republic (CAR)',
  'cg': 'Republic of the Congo',
  'ch': 'Switzerland',
  'ci': "Côte d'Ivoire (Ivory Coast)",
  'ck': 'Cook Islands',
  'cl': 'Chile',
  'cm': 'Cameroon',
  'cn': 'China',
  'co': 'Colombia',
  'cr': 'Costa Rica',
  'cu': 'Cuba',
  'cv': 'Cape Verde',
  'cw': 'Curaçao',
  'cx': 'Christmas Island',
  'cy': 'Cyprus',
  'cz': 'Czech Republic',
  'de': 'Germany',
  'dj': 'Djibouti',
  'dk': 'Denmark',
  'dm': 'Dominica',
  'do': 'Dominican Republic',
  'dz': 'Algeria',
  'ec': 'Ecuador',
  'ee': 'Estonia',
  'eg': 'Egypt',
  'eh': 'Western Sahara',
  'er': 'Eritrea',
  'es': 'Spain',
  'et': 'Ethiopia',
  'eu': 'European Union',
  'fi': 'Finland',
  'fj': 'Fiji',
  'fk': 'Falkland Islands (Islas Malvinas)',
  'fm': 'Federated States of Micronesia',
  'fo': 'Faroe Islands',
  'fr': 'France',
  'ga': 'Gabon',
  'gb': 'United Kingdom (Great Britain)',
  'gd': 'Grenada',
  'ge': 'Georgia',
  'gf': 'French Guiana',
  'gg': 'Guernsey',
  'gh': 'Ghana',
  'gi': 'Gibraltar',
  'gl': 'Greenland',
  'gm': 'Gambia',
  'gn': 'Guinea',
  'gp': 'Guadeloupe',
  'gq': 'Equatorial Guinea',
  'gr': 'Greece',
  'gs': 'South Georgia and the South Sandwich Islands',
  'gt': 'Guatemala',
  'gu': 'Guam',
  'gw': 'Guinea-Bissau',
  'gy': 'Guyana',
  'hk': 'Hong Kong',
  'hm': 'Heard Island and McDonald Islands',
  'hn': 'Honduras',
  'hr': 'Croatia',
  'ht': 'Haiti',
  'hu': 'Hungary',
  'id': 'Indonesia',
  'ie': 'Ireland',
  'il': 'Israel',
  'im': 'Isle of Man',
  'in': 'India',
  'io': 'British Indian Ocean Territory',
  'iq': 'Iraq',
  'ir': 'Iran',
  'is': 'Iceland',
  'it': 'Italy',
  'je': 'Jersey',
  'jm': 'Jamaica',
  'jo': 'Jordan',
  'jp': 'Japan',
  'ke': 'Kenya',
  'kg': 'Kyrgyzstan',
  'kh': 'Cambodia',
  'ki': 'Kiribati',
  'km': 'Comoros',
  'kn': 'Saint Kitts and Nevis',
  'kp': "North Korea (Democratic People's Republic of Korea)",
  'kr': 'South Korea',
  'kw': 'Kuwait',
  'ky': 'Cayman Islands',
  'kz': 'Kazakhstan',
  'la': "Laos (Lao People's Democratic Republic)",
  'lb': 'Lebanon',
  'lc': 'Saint Lucia',
  'li': 'Liechtenstein',
  'lk': 'Sri Lanka',
  'lr': 'Liberia',
  'ls': 'Lesotho',
  'lt': 'Lithuania',
  'lu': 'Luxembourg',
  'lv': 'Latvia',
  'ly': 'Libya',
  'ma': 'Morocco',
  'mc': 'Monaco',
  'md': 'Moldova',
  'me': 'Montenegro',
  'mf': 'Saint Martin (French part)',
  'mg': 'Madagascar',
  'mh': 'Marshall Islands',
  'mk': 'North Macedonia',
  'ml': 'Mali',
  'mm': 'Myanmar (Burma)',
  'mn': 'Mongolia',
  'mo': 'Macau',
  'mq': 'Martinique',
  'mt': 'Malta',
  'mu': 'Mauritius',
  'mv': 'Maldives',
  'mx': 'Mexico',
  'mz': 'Mozambique',
  'na': 'Namibia',
  'ng': 'Nigeria',
  'ni': 'Nicaragua',
  'nl': 'Netherlands',
  'no': 'Norway',
  'np': 'Nepal',
  'nz': 'New Zealand',
  'om': 'Oman',
  'pa': 'Panama',
  'pe': 'Peru',
  'pf': 'French Polynesia',
  'pg': 'Papua New Guinea',
  'ph': 'Philippines',
  'pk': 'Pakistan',
  'pl': 'Poland',
  'ps': 'Palestine',
  'pt': 'Portugal',
  'py': 'Paraguay',
  're': 'Réunion',
  'ro': 'Romania',
  'rs': 'Serbia',
  'ru': 'Russia',
  'rw': 'Rwanda',
  'sa': 'Saudi Arabia',
  'se': 'Sweden',
  'sg': 'Singapore',
  'si': 'Slovenia',
  'sk': 'Slovakia',
  'sl': 'Sierra Leone',
  'sm': 'San Marino',
  'so': 'Somalia',
  'ss': 'South Sudan',
  'sv': 'El Salvador',
  'sy': 'Syria',
  'th': 'Thailand',
  'tj': 'Tajikistan',
  'tk': 'Tokelau',
  'tl': 'Timor-Leste (East Timor)',
  'tm': 'Turkmenistan',
  'tn': 'Tunisia',
  'to': 'Tonga',
  'tr': 'Turkey',
  'tt': 'Trinidad and Tobago',
  'tv': 'Tuvalu',
  'tw': 'Taiwan',
  'tz': 'Tanzania',
  'ua': 'Ukraine',
  'ug': 'Uganda',
  'us': 'United States of America (USA)',
  'uy': 'Uruguay',
  'uz': 'Uzbekistan',
  've': 'Venezuela',
  'vn': 'Vietnam',
  'wf': 'Wallis and Futuna',
  'ye': 'Yemen',
  'za': 'South Africa',
  'zm': 'Zambia',
  'zw': 'Zimbabwe',
};
