name: raven_front
description: A Ravencoin wallet for iOS and Android

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+0

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  date_format: ^2.0.4
  firebase_core: ^1.10.0
  firebase_crashlytics: ^2.4.1
  firebase_messaging: ^11.2.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.0
  flutter_spinkit: ^5.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_svg: ^1.0.0
  material_design_icons_flutter: ^5.0.6595
  fnv: ^1.0.1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.0
  ulid: ^2.0.0
  url_launcher: ^6.0.10
  ravencoin_wallet: ^3.0.0
  path_provider: ^2.0.5 # to get the correct path to store our file
  permission_handler: ^8.2.5 # to handle the permissions to read and write files
  share: ^2.0.4 # to share the file that we create // old
  file_picker: ^4.1.5 # to import the file that we saved
  intl: ^0.17.0
  mockito: ^5.0.17 # just for testing
  intersperse: ^2.0.0
  flutter_keyboard_visibility: ^5.2.0
  lottie: ^1.2.2
  shimmer: ^2.0.0
  flutter_windowmanager: ^0.2.0 # percision disable screenshot android
  rxdart: ^0.27.3

  # raven_back:
  #   git: https://github.com/moontreeapp/raven_back.git
  raven_electrum: ^2.0.0
  reservoir: ^2.0.0

dependency_overrides:
  raven_back:
    path: ../raven_back
  raven_electrum:
    path: ../raven_electrum
  reservoir:
    path: ../reservoir
  ravencoin_wallet:
    path: ../ravencoin_wallet
  #screenshot_callback:
  #  git:
  #    url: https://github.com/ousvat/flutter_screenshot_callback.git
  #    #url: https://github.com/devplanet-dp/flutter_screenshot_callback.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: ^1.17.10

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  #To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icons/
    - assets/icons/create/
    - assets/icons/discord/
    - assets/icons/extras/
    - assets/icons/import_export/
    - assets/icons/manage/
    - assets/icons/menu/
    - assets/icons/network/
    - assets/icons/receive/
    - assets/icons/scan/
    - assets/icons/send/
    - assets/icons/status/
    - assets/icons/swap/
    - assets/icons/user_level/
    - assets/icons/wallet/
    - assets/logo/
    - assets/spinner/
    - assets/splash/
    - assets/status/
    - .env

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito/Nunito-VariableFont_wght.ttf
        - asset: fonts/Nunito/Nunito-Italic-VariableFont_wght.ttf
          style: italic
        - asset: fonts/Nunito/static/Nunito-Regular.ttf
          weight: 400
        - asset: fonts/Nunito/static/Nunito-Italic.ttf
          style: italic
        - asset: fonts/Nunito/static/Nunito-Black.ttf
          weight: 900
        - asset: fonts/Nunito/static/Nunito-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: fonts/Nunito/static/Nunito-Bold.ttf
          weight: 700
        - asset: fonts/Nunito/static/Nunito-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: fonts/Nunito/static/Nunito-ExtraBold.ttf
          weight: 800
        - asset: fonts/Nunito/static/Nunito-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: fonts/Nunito/static/Nunito-ExtraLight.ttf
          weight: 200
        - asset: fonts/Nunito/static/Nunito-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: fonts/Nunito/static/Nunito-Light.ttf
          weight: 300
        - asset: fonts/Nunito/static/Nunito-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/Nunito/static/Nunito-Medium.ttf
          weight: 500
        - asset: fonts/Nunito/static/Nunito-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/Nunito/static/Nunito-SemiBold.ttf
          weight: 600
        - asset: fonts/Nunito/static/Nunito-SemiBoldItalic.ttf
          style: italic
          weight: 600
