name: client_back
description: Ravencoin wallet backend library
version: 1.0.0

environment:
  sdk: '>=2.15.0<4.0.0'

dependencies:
  bs58: ^1.0.2
  bs58check: ^1.0.2
  collection: ^1.17.1
  crypto: ^3.0.2
  encrypt: ^5.0.1
  equatable: ^2.0.5
  hive: ^2.2.3
  ordered_set: ^5.0.1
  pointycastle: ^3.6.2
  quiver: ^3.1.0
  rxdart: ^0.27.5
  sorted_list: ^1.0.0
  http: ^0.13.5
  ulid: ^2.0.0
  tuple: ^2.0.0
  intl: ^0.17.0
  #serverpod_client: ^0.9.20
  serverpod_client: ^1.1.0
  electrum_adapter: ^2.0.4
  proclaim: ^4.1.1
  wallet_utils: ^3.1.3
  moontree_utils: ^1.1.7
  date_format: ^2.0.7
  bip39: ^1.0.6
  convert: ^3.0.2
  stream_channel: ^2.1.0

dependency_overrides:
  #proclaim:
  #  path: ../../proclaim
  #electrum_adapter:
  #  path: ../../electrum_adapter
  #wallet_utils:
  #  path: ../../wallet_utils
  #moontree_utils:
  #  path: ../../moontree_utils

dev_dependencies:
  build_runner: ^2.4.4
  matcher: ^0.12.16
  dotenv: ^3.0.0
  hive_generator: ^1.1.3
  pedantic: ^1.11.1
  test: ^1.17.12
#
#  # flutter packages upgrade
#
#  PS C:\moontree\moontreeV1\client_back> flutter packages upgrade
#Resolving dependencies... (2.4s)
#  _fe_analyzer_shared 47.0.0 (61.0.0 available)
#  analyzer 4.7.0 (5.13.0 available)
#> args 2.4.1 (was 2.3.1)
#  asn1lib 1.4.0
#> async 2.11.0 (was 2.10.0)
#  base_x 2.0.0
#> bech32 0.2.2 (was 0.2.1)
#  bip32 2.0.0
#  bip39 1.0.6
#  boolean_selector 2.1.1
#  bs58 1.0.2
#  bs58check 1.0.2
#> build 2.4.0 (was 2.3.1)
#  build_config 1.1.1
#  build_daemon 4.0.0
#  build_resolvers 2.0.10 (2.2.0 available)
#  build_runner 2.4.4
#> build_runner_core 7.2.9 (was 7.2.7)
#  built_collection 5.1.1
#> built_value 8.6.0 (was 8.4.2)
#> checked_yaml 2.0.3 (was 2.0.1)
#  clock 1.1.1
#> code_builder 4.5.0 (was 4.3.0)
#  collection 1.17.2
#> convert 3.1.1 (was 3.0.2)
#> coverage 1.6.3 (was 1.6.1)
#> crypto 3.0.3 (was 3.0.2)
#  dart_style 2.2.4 (2.3.1 available)
#  date_format 2.0.7
#  dotenv 3.0.0 (4.1.0 available)
#  electrum_adapter 2.0.4
#  encrypt 5.0.1
#  equatable 2.0.5
#> file 7.0.0 (was 6.1.4)
#> fixnum 1.1.0 (was 1.0.1)
#  frontend_server_client 3.2.0
#> glob 2.1.2 (was 2.1.1)
#> graphs 2.3.1 (was 2.2.0)
#  hex 0.2.0
#  hive 2.2.3
#  hive_generator 1.1.3 (2.0.0 available)
#> http 0.13.6 (was 0.13.5) (1.0.0 available)
#  http_multi_server 3.2.1
#  http_parser 4.0.2
#  intl 0.17.0 (0.18.1 available)
#> io 1.0.4 (was 1.0.3)
#  js 0.6.7
#> json_annotation 4.8.1 (was 4.7.0)
#  json_rpc_2 3.0.2
#> logging 1.2.0 (was 1.1.0)
#  matcher 0.12.16
#  meta 1.9.1
#> mime 1.0.4 (was 1.0.3)
#  moontree_utils 1.1.2
#> node_preamble 2.0.2 (was 2.0.1)
#  ordered_set 5.0.1
#  package_config 2.1.0
#> path 1.8.3 (was 1.8.2)
#  pedantic 1.11.1 (discontinued replaced by lints)
#> pointycastle 3.7.3 (was 3.6.2)
#  pool 1.5.1
#  proclaim 4.1.1
#> pub_semver 2.1.4 (was 2.1.3)
#> pubspec_parse 1.2.3 (was 1.2.1)
#> quiver 3.2.1 (was 3.1.0)
#  rxdart 0.27.7
#> serverpod_client 1.1.1 (was 1.1.0)
#> serverpod_serialization 1.1.1 (was 1.1.0)
#> shelf 1.4.1 (was 1.4.0)
#> shelf_packages_handler 3.0.2 (was 3.0.1)
#> shelf_static 1.1.2 (was 1.1.1)
#> shelf_web_socket 1.0.4 (was 1.0.3)
#  sorted_list 1.0.0
#  source_gen 1.2.6 (1.3.2 available)
#  source_helper 1.3.3
#  source_map_stack_trace 2.1.1
#> source_maps 0.10.12 (was 0.10.11)
#> source_span 1.10.0 (was 1.9.1)
#  stack_trace 1.11.0
#  stream_channel 2.1.1
#  stream_transform 2.1.0
#  string_scanner 1.2.0
#  term_glyph 1.2.1
#  test 1.24.3
#  test_api 0.6.0
#  test_core 0.5.3
#> timing 1.0.1 (was 1.0.0)
#  tuple 2.0.1
#> typed_data 1.3.2 (was 1.3.1)
#  ulid 2.0.0
#  uuid 3.0.7
#> vm_service 11.6.0 (was 9.4.0)
#  wallet_utils 3.1.2
#> watcher 1.1.0 (was 1.0.2)
#  web_socket_channel 2.4.0
#  webkit_inspection_protocol 1.2.0
#> yaml 3.1.2 (was 3.1.1)
#Changed 39 dependencies!
#1 package is discontinued.
#9 packages have newer versions incompatible with dependency constraints.
#Try `flutter pub outdated` for more information.
